[package]
name = "Task04-2R"
version = "0.1.0"
authors = ["Dereandor <torstehs@stud.ntnu.no>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
